 // Project data mapped from F:\UI\FlexClip\Png\切图素材\作品集素材
 
 const projectBase = "/assets/projects";
 
 function img(path) {
   return `${projectBase}${path}`;
 }
 
 export const flexclipProject = {
   id: "flexclip",
   title: "FlexClip AI",
  titleZh: "FlexClip AI",
   meta: "AI Product Design · Web / Mobile · Design System",
  metaZh: "AI 产品设计 · Web / 移动端 · 设计系统",
   summary:
     "Designed for a video product serving over ten million global users, including 0→1 AI tools across image, video and audio generation workflows. Involved in AI tool UI from concept through continuous iteration, covering text-to-video, image generation, auto subtitles, background removal, face replacement and more. Also handled Web and mobile editor UI iteration, partner pages and campaign graphics.",
  summaryZh:
     "参与千万级在线视频剪辑产品设计，负责 AI 工具从 0 到 1 的搭建与迭代，覆盖图生图、文生视频、AI 字幕、去背景、换脸等多功能界面设计。同时负责 Web 端及移动端 UI 迭代、外联需求与活动专题设计。",
   tags: ["AI Tools", "Web", "Mobile", "Design System"],
   categories: [
     {
       name: "AI Web Tools",
         nameZh: "AI 网页工具",
       description: "Web-based AI tool interfaces and tool pages",
         descriptionZh: "基于网页的 AI 工具界面与功能页面",
       images: [
         { src: img("/flexclip/ai-tools-web/%E7%BB%84%20488@1.5x.png"), caption: "AI Image Generation & Photo Editing",
        captionZh: "AI 图生图 & 照片编辑" },
         { src: img("/flexclip/ai-tools-web/%E7%BB%84%20489@1.5x.png"), caption: "Text/Image to Video & Effects",
        captionZh: "文生视频 & 视频特效" },
         { src: img("/flexclip/ai-tools-web/%E7%BB%84%20491@1.5x.png"), caption: "AI Smart Templates & Voice Clone",
        captionZh: "AI 智能模板 & 语音克隆" },
         { src: img("/flexclip/ai-tools-web/%E7%BB%84%20490@1.5x.png"), caption: "Background Removal & Image Upscale",
        captionZh: "去背景 & 无损放大与上色" },
       ],
     },
     {
       name: "Mobile",
         nameZh: "移动端",
       description: "FlexClip mobile app (FlexPix) UI design",
         descriptionZh: "FlexClip 移动端（FlexPix）UI 设计",
       images: [
         { src: img("/flexclip/mobile/%E7%BB%84%20492@1.5x.png"), caption: "Version iteration & Banner design",
        captionZh: "版本迭代优化 & Banner 设计" },
         { src: img("/flexclip/mobile/%E7%BB%84%201@1.5x.png"), caption: "AI video feature showcase",
        captionZh: "AI 视频功能板块展示" },
         { src: img("/flexclip/mobile/%E8%92%99%E7%89%88%E7%BB%84%206@1.5x.png"), caption: "AI photo section preview",
        captionZh: "AI 照片板块部分缩略展示" },
         { src: img("/flexclip/mobile/Frame%203@1.5x.png"), caption: "Video effects section",
        captionZh: "视频特效板块部分缩略展示" },
         { src: img("/flexclip/mobile/%E7%BB%84%20463@1.5x.png"), caption: "Background removal feature",
        captionZh: "去背景功能部分缩略展示" },
       ],
     },
     {
       name: "Web Pages",
       layout: "masonry",
         nameZh: "网页设计",
       description: "Independent landing pages and campaign pages",
         descriptionZh: "独立着陆页与活动专题页面设计",
       images: [
         { src: img("/flexclip/web-pages/home.png"), caption: "FlexClip Homepage",
         captionZh: "FlexClip 首页" },
         { src: img("/flexclip/web-pages/1.png"), caption: "AI tool landing page",
         captionZh: "AI 工具着陆页" },
         { src: img("/flexclip/web-pages/2.png"), caption: "Feature page design",
         captionZh: "功能页面设计" },
         { src: img("/flexclip/web-pages/3.png"), caption: "Product showcase",
         captionZh: "产品展示页面" },
         { src: img("/flexclip/web-pages/AI%20Background%20Remover%20Online.png"), caption: "AI Background Remover",
         captionZh: "AI 去背景" },
         { src: img("/flexclip/web-pages/AI%20Photo%20Enhancer.png"), caption: "AI Photo Enhancer",
         captionZh: "AI 图片增强" },
         { src: img("/flexclip/web-pages/ai%E8%A7%86%E9%A2%91%E9%85%8D%E9%9F%B3%E7%9D%80%E9%99%86%E9%A1%B5.png"), caption: "AI Video Dubbing LP",
         captionZh: "AI 视频配音着陆页" },
         { src: img("/flexclip/web-pages/AI%E8%AF%81%E4%BB%B6%E7%85%A7%E7%9D%80%E9%99%86%E9%A1%B5.png"), caption: "AI ID Photo LP",
         captionZh: "AI 证件照着陆页" },
         { src: img("/flexclip/web-pages/ai%20muscle.png"), caption: "AI Muscle Generator",
         captionZh: "AI 肌肉生成器" },
         { src: img("/flexclip/web-pages/AI%20%E5%9C%A8%E7%BA%BF%E5%A4%A9%E7%A9%BA%E6%9B%BF%E6%8D%A2.png"), caption: "AI Sky Replacement",
         captionZh: "AI 在线天空替换" },
         { src: img("/flexclip/web-pages/AI%E6%8D%A2%E5%8F%91%E7%9D%80%E9%99%86%E9%A1%B5.png"), caption: "AI Hairstyle Change LP",
         captionZh: "AI 换发着陆页" },
         { src: img("/flexclip/web-pages/Free%20AI%20Pixel%20Art%20Generator%20Online.png"), caption: "AI Pixel Art Generator",
         captionZh: "AI 像素艺术生成器" },
       ],
     },
   ],
 };
 
 export const beanTennisProject = {
   id: "bean-tennis",
   title: "Bean Tennis",
  titleZh: "豆子网球",
   meta: "Brand Identity · Mini Program · UX",
  metaZh: "品牌视觉 · 小程序 · 用户体验",
   summary:
     "A youthful, scalable visual and product system for Chengdu's first 24-hour smart tennis venue. Defined the brand visual identity and designed the full mini-program UI — covering venue booking, membership, tennis skill testing, rankings, live video casting, and coach booking — to connect courts, coaching, courses and performance data.",
  summaryZh:
     "豆子网球是重庆首家 24 小时智能网球自助学练馆。从品牌视觉系统到小程序完整 UI 设计，涵盖场地预约、会员系统、网球水平测试、运动排行榜、现场视频投屏、私教预约等功能，连接场馆、课程与运动数据。",
   tags: ["Brand VI", "Mini Program", "UX", "Visual System"],
   categories: [
     {
       name: "Brand Identity",
       layout: "single",
         nameZh: "品牌视觉",
       description: "Visual system including logo, colors, typography and brand standards",
         descriptionZh: "包含标志、色彩、字体与品牌规范的视觉系统",
       images: [
         { src: img("/bean-tennis/1.png"), caption: "Brand logo primary",
         captionZh: "品牌主标志" },
         { src: img("/bean-tennis/2.png"), caption: "Logo color variants",
         captionZh: "标志色彩变体" },
         { src: img("/bean-tennis/3.png"), caption: "Visual identity system",
         captionZh: "视觉识别系统" },
         { src: img("/bean-tennis/4.png"), caption: "Logo usage guidelines",
         captionZh: "标志使用规范" },
         { src: img("/bean-tennis/5.png"), caption: "Brand collateral",
         captionZh: "品牌应用物料" },
         { src: img("/bean-tennis/6.png"), caption: "Typography system",
         captionZh: "字体系统" },
         { src: img("/bean-tennis/7.png"), caption: "Brand application",
         captionZh: "品牌应用展示" },
         { src: img("/bean-tennis/8.png"), caption: "Brand color palette",
         captionZh: "品牌色彩体系" },
         { src: img("/bean-tennis/9.png"), caption: "Iconography system",
         captionZh: "图标系统" },
       ],
     },
     {
       name: "UI Screens",
       layout: "single",
         nameZh: "界面展示",
       description: "Main mini-program UI pages and user flows",
         descriptionZh: "小程序主要 UI 页面与用户流程",
       images: [
         { src: img("/bean-tennis/10.png"), caption: "Mini program home",
         captionZh: "小程序首页" },
         { src: img("/bean-tennis/11.png"), caption: "Venue selection",
         captionZh: "场地选择" },
         { src: img("/bean-tennis/12.png"), caption: "Booking flow",
         captionZh: "预约流程" },
         { src: img("/bean-tennis/13.png"), caption: "Membership & profile",
         captionZh: "会员与个人中心" },
         { src: img("/bean-tennis/14.png"), caption: "Course & training",
         captionZh: "课程与训练" },
         { src: img("/bean-tennis/15.png"), caption: "Coach listing",
         captionZh: "教练列表" },
         { src: img("/bean-tennis/16.png"), caption: "Activity & events",
         captionZh: "活动与赛事" },
         { src: img("/bean-tennis/17.png"), caption: "Payment & orders",
         captionZh: "支付与订单" },
         { src: img("/bean-tennis/18.png"), caption: "Notifications center",
         captionZh: "消息中心" },
       ],
     },
     {
       name: "Features",
       layout: "single",
         nameZh: "特色功能",
       description: "Core unique features — tennis test, rankings, video cast and coach booking",
         descriptionZh: "核心特色功能 — 水平测试、排行榜、视频投屏、教练预约",
       images: [
         { src: img("/bean-tennis/19.png"), caption: "Tennis skill test intro",
         captionZh: "网球水平测试介绍" },
         { src: img("/bean-tennis/20.png"), caption: "Test result & analysis",
         captionZh: "测试结果与分析" },
         { src: img("/bean-tennis/21.png"), caption: "Leaderboard rankings",
         captionZh: "运动排行榜" },
         { src: img("/bean-tennis/22.png"), caption: "Live video casting control",
         captionZh: "现场视频投屏控制" },
         { src: img("/bean-tennis/23.png"), caption: "Video playback on court screen",
         captionZh: "场地屏幕视频播放" },
         { src: img("/bean-tennis/24.png"), caption: "Coach profile detail",
         captionZh: "教练详情" },
         { src: img("/bean-tennis/25.png"), caption: "Coach booking calendar",
         captionZh: "教练预约日历" },
         { src: img("/bean-tennis/26.png"), caption: "Booking confirmation",
         captionZh: "预约确认" },
         { src: img("/bean-tennis/27.png"), caption: "Courtside screen UI",
         captionZh: "球场屏幕 UI" },
         { src: img("/bean-tennis/28.png"), caption: "Sports data dashboard",
         captionZh: "运动数据仪表盘" },
         { src: img("/bean-tennis/29.png"), caption: "QR code check-in",
         captionZh: "二维码签到" },
       ],
     },
   ],
 };
